services:
  - type: web
    name: autoinspect-api
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install --no-cache-dir torch==2.9.1 torchvision==0.24.1 --index-url https://download.pytorch.org/whl/cpu && pip install --no-cache-dir -r backend/requirements.txt
    startCommand: bash start.sh
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: AutoInspect
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: autoinspect-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: autoinspect-redis
          property: connectionString
      - key: FRONTEND_URL
        sync: false
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MAX_FILE_SIZE_MB
        value: "10"

  - type: web
    name: autoinspect-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false

  - type: keyvalue
    name: autoinspect-redis
    region: singapore
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow Redis connections

databases:
  - name: autoinspect-db
    region: singapore
    plan: free
